# Generated by Django 5.0.6 on 2024-06-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='banner',
            field=models.ImageField(blank=True, default='Fallback.png', upload_to=''),
        ),
    ]
