# Generated by Django 5.0.6 on 2024-06-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_articles_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='banner',
            field=models.ImageField(blank=True, default='Fallback.jpg', upload_to='media/'),
        ),
    ]
